name: "Static Analysis"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  static-analysis-phpstan:
    name: "PHPStan - ${{ matrix.package }} / ${{ matrix.dependency }} ${{ matrix.dependency-version }}"
    runs-on: "ubuntu-24.04"

    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "math"
            dependency: "brick/math"
            dependency-version: "^0.15"
          - package: "math"
            dependency: "brick/math"
            dependency-version: "^0.16"
          - package: "math"
            dependency: "brick/math"
            dependency-version: "^0.17"
          - package: "math"
            dependency: "brick/math"
            dependency-version: "^0.18"
          - package: "money"
            dependency: "brick/money"
            dependency-version: "^0.13"
          - package: "money"
            dependency: "brick/money"
            dependency-version: "^0.14"

    defaults:
      run:
        working-directory: "${{ matrix.package }}"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v7"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.4"
          tools: "cs2pr"

      - name: "Select ${{ matrix.dependency }} ${{ matrix.dependency-version }}"
        run: "composer require --no-interaction --no-update ${{ matrix.dependency }}:${{ matrix.dependency-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@4.0.0"
        with:
          working-directory: "${{ matrix.package }}"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
